[database]
# Jeśli używasz innej nazwy instancji na PC, zmień .\SQLEXPRESS na np. localhost albo (localdb)\MSSQLLocalDB
server = localhost\VSQLPL179ANA
database = mSprzetDB
driver = SQL Server
trusted_connection = yes
autocommit = yes

[email]
cc = test@twojakorporacja.pl